### ISSUE TITLE
Report to PM Team (Yadi dan Jakson) dan finalisasi dokumen (Ureq, Bisnis proses, Project Team dan Timeline)

### ISSUE THREAD

**Issue by matsuras** [itappsjas/K3-Project#1]
Handy dan Vira tolong koordinasikan dengan Yadi dan Jakson bahan presentasi tersebut dan dipastikan mereka mepresentasikan ke Pak Irlandi dan Pak Bayu

**Comment by Handy182** [comment]
Untuk user requirement sudah di diskusikan dengan team SQA (Yadi dan Jekson), mereka setuju dengan PPT yang di ajukan.Saat ini tinggal menunggu time line yang akan disesuaikan oleh team SQA.

**Comment by Budiyantoangga** [comment]
Nanti untuk dokumen nya sebelum di rilis, di presentasikan ke Mas Yadi juga ya bang, agar flow nya sesuai dan mas Yadi nya juga acknowledge untuk flow yang sudah di buat. 

Kalau sudah oke Mas Yadi nya ttd di dokumen nya

**Comment by Handy182** [comment]
Oke, pasti di presentasikan dulu ke tim SQA sebelum rilis,tinggal nunggu time line aja dari tim SQA

**Comment by Budiyantoangga** [comment]
**Current Status :** 
1. User Requirements (Done)
2. Business Process sudah di verifikasi dan di setujui oleh team K3 (Done)
3. Project Team : 
     **Advisor** : Irlandie
     **PM** : M. Supriyadi
     **Co PM** : Jekson
     **BA** : Handy & Vira
     **Dev** : Masudi

    **Issue** :  Diskusikan dengan pak Landi untuk pak Risang di dalam struktur project K3 sebagai apa ?
4. Timeline : 
    - Dok User Requirements  (30 Des 24 Final -> Sudah ada ttd struktur membernya)
    - Development (1st week - 2nd week)
    - UAT (Minggu ke 3 Jan 2025) -> Diskusi untuk skenario UAT ?
    - Go Live (1 Feb 2025)

    **Issue** : 
    1. Push Yadi untuk dokumen ureq-nya sudah sesuai dan ditandatangi oleh seluruh member.
    2. Buat Timeline dalam bentuk Gant Chart.
    3. Buat Presentasi untuk Internal dan pak Tedy. (Estimasi 06 Jan 2025)
